services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: study-flow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: study_flow_db
      POSTGRES_USER: study_flow_user
      POSTGRES_PASSWORD: study_flow_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - study-flow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U study_flow_user -d study_flow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: study-flow-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - study-flow-network
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Study Flow API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-flow-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://study_flow_user:study_flow_password@postgres:5432/study_flow_db
      
      # Qdrant Configuration
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_API_KEY: 
      
      # OpenAI Configuration
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
      OPENAI_CHAT_MODEL: o3-mini
      OPENAI_MAX_TOKENS: 4000
      OPENAI_TEMPERATURE: 0.7
      
      # RAG Configuration
      RAG_CHUNK_SIZE: 1000
      RAG_CHUNK_OVERLAP: 200
      RAG_MAX_CHUNKS: 5
      RAG_SIMILARITY_THRESHOLD: 0.4
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    volumes: []
    networks:
      - study-flow-network
    depends_on:
      - postgres
      - qdrant
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  study-flow-network:
    driver: bridge
